### ISSUE TITLE
Add Compatibility to Java17

### ISSUE THREAD

**Issue by stianrincon** [luisgoncalves/xades4j#239] opened 2021-11-30 15:30 UTC
Since Java 16 reflective access was turn off by default, but we still can do this:

`--illegal-access=permit`

The problem with Java 17 is reflective access was removed completely, meaning `--illegal-access=permit` cannot be used any more.

It would be nice if we can use xades4j with java 17.

**Comment by luisgoncalves** [comment] 2021-12-02 10:35
I'll investigate where the deps on reflective access come from and how to circumvent them.

**Comment by luisgoncalves** [comment] 2021-12-03 23:04
@stianrincon Can you provide a stack trace of one of the errors in Java 17? Is it when using the PKCS11 key provider? Tried running the tests in Java 16 and 17 and the build passes (https://github.com/luisgoncalves/xades4j/pull/240). However, those build **do not** run the tests that use the PKCS11 provider.

Btw, what version of xades4j are you using?

**Comment by stianrincon** [comment] 2021-12-04 16:37
Hi @luisgoncalves  Thank you so much for such as fast response, 

Answering your questions:
1. xades4j version 1.6.0
2. I'm signing a document using XadesEpesSigningProfile
3. this is the error trace:

```
        xades4j.utils.XadesProfileResolutionException: java.lang.ExceptionInInitializerError
        at xades4j.utils.XadesProfileCore.getInstance(XadesProfileCore.java:223)
        at xades4j.production.XadesSigningProfile.newSigner(XadesSigningProfile.java:113)
```

Once again thank you so much, if you guide me I can help you creating a PR.

**Comment by luisgoncalves** [comment] 2021-12-04 18:01
Can you get the nested exceptions (or at least the message) of that `ExceptionInInitializerError`? That would help understand the root cause.

How did you find that there were problems with reflective accesses?

**Comment by luisgoncalves** [comment] 2021-12-04 23:30
I was able to reproduce the illegal reflective access when using `PKCS11KeyStoreKeyingDataProvider`, due to loading of `sun.security.pkcs11.SunPKCS11`. Are you using `PKCS11KeyStoreKeyingDataProvider` or did you hit the illegal access in another scenario?

Fixing this requires using new APIs  in Java's `Provider` class, which requires Java 9+, which is a breaking change (currently only Java 8 is required). It's probably about time that's done, but I need to think a bit more and eventually come up with a plan for a new major release (which can include other long due cleanups).

**Comment by luisgoncalves** [comment] 2021-12-07 17:16
@stianrincon did you have a chance to see my comments above? Which error are you hitting?

**Comment by stianrincon** [comment] 2021-12-11 21:59
Hi @luisgoncalves I made a debug and... the error is thrown in this exact line https://github.com/google/guice/blob/2a45130f8962e21a3df075c42d1c4c5c61ec5bba/src/com/google/inject/BindingProcessor.java#L229

Now, this is what I have in my code:
```
        var xadesEpesSigningProfile = new XadesEpesSigningProfile(getKeyingDataProvider(), signaturePolicyInfoProvider);
        xadesEpesSigningProfile.withSignaturePropertiesProvider(signaturePropertiesProvider);
        xadesEpesSigningProfile.withBasicSignatureOptions(new BasicSignatureOptions().signKeyInfo(true).includePublicKey(true)
                .includeSigningCertificate(SigningCertificateMode.SIGNING_CERTIFICATE));
        xadesEpesSigningProfile..newSigner()      
```

and the error is thrown when calling `newSigner()`

**Comment by luisgoncalves** [comment] 2021-12-11 23:02
Hi @stianrincon,

Earlier you mentioned the following error:

```
xades4j.utils.XadesProfileResolutionException: java.lang.ExceptionInInitializerError
        at xades4j.utils.XadesProfileCore.getInstance(XadesProfileCore.java:223)
        at xades4j.production.XadesSigningProfile.newSigner(XadesSigningProfile.java:113)
```

Can you get the causes of that exception? `ExceptionInInitializerError` is thrown when there's an error in a static constructor/class initializer, so I'd like to know what the original exception is.

Also:
- What's your Java version with details (i.e. output of `java --version`)?
- Can you run in Java 16 with `--illegal-access=debug` and post the warnings/details here?
- Are you using the `PKCS11KeyStoreKeyingDataProvider` class from xades4j ? What do you return from `getKeyingDataProvider()`?

**Comment by stianrincon** [comment] 2021-12-12 01:31
The exception `ExceptionInInitializerError` is thrown in this method https://github.com/google/guice/blob/2a45130f8962e21a3df075c42d1c4c5c61ec5bba/src/com/google/inject/BindingProcessor.java#L229

* Java version:
`openjdk 16.0.2 2021-07-20`

* Are you using the PKCS11KeyStoreKeyingDataProvider
No I'm using `xades4j/providers/impl/FileSystemKeyStoreKeyingDataProvider.java`

* getKeyingDataProvider():
```
keyingDataProvider =
                    new FileSystemKeyStoreKeyingDataProvider(pkcs12, "certificate.p12", new FirstCertificateSelector(),
                            new DirectPasswordProvider("XXXXXXXX"), new DirectPasswordProvider("XXXXXXXXX"),
                            true);
```

* Java 16 with --illegal-access=debug

```
An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.ReflectUtils$2 (/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/2.0/a4c67006178262122e93121e94fff306fcf0cda1/guice-2.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by luisgoncalves** [comment] 2021-12-12 12:36
Ah, the illegal reflective access is coming from Guice itself. When you first pointed to Guice I thought the exception could be surfacing there but be caused by something in xades4j. 

Anyway, a few days ago xades4j 1.7.0 was released, which depends on a more recent version of Guice that shouldn't have those issues. The Guice upgrade was done some time ago, but I hadn't released a new version of xades4j yet.

The builds I did on Java 16 and 17 passed, and those were based on the `master` branch, which included the aforementioned changes. Can you try the latest xades4j version?

Can you try 1.7.0

**Comment by stianrincon** [comment] 2021-12-12 18:45
Thank you so so much, with the new version 1.7.0 and java16 the command `--illegal-access=permit` is not needed. I'll try with java17 and I'll let you know.

Thanks man!!!

**Comment by luisgoncalves** [comment] 2021-12-12 20:17
Great. I'm confident it works well. 

I'll close the issue. Re-open if needed.

**Closed by luisgoncalves** 2021-12-12 20:17 UTC

**Comment by stianrincon** [comment] 2021-12-15 01:55
@luisgoncalves tested  it with java17 and works like a charm.... THANK YOU!!!!
