### ISSUE TITLE
.ReferenceValueException: Reference '#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-signedprops' cannot be validated

### ISSUE THREAD

**Issue by Mariluz08** [luisgoncalves/xades4j#169] opened 2018-10-18 20:58 UTC
Hi 
I have a problem, I signature the xml, but DIAN rejects me, 
com.indra.mmdd.signature.exceptions.ValidateException: xades4j.verification.ReferenceValueException: Reference '#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-signedprops' cannot be validated

the signature xml is:

-<ds:Signature Id="xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">

-<ds:SignedInfo>

<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>

-<ds:Reference Id="xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-ref0" URI="">

-<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>9Qi81Ftu9iJkBADDQnP8nr3yUVxMgT510lZ5wbEJUtM=</ds:DigestValue>
</ds:Reference>
-<ds:Reference URI="#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-keyinfo">
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>McAI9vm6HJHyZLgan/la1WB61qNGXhlbKxjoX5NKoVM=</ds:DigestValue>
</ds:Reference>

-<ds:Reference URI="#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-signedprops" Type="http://uri.etsi.org/01903#SignedProperties">

-<ds:Transforms>

<ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>

</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>Dg4QCFvLEGb88GRC6Pr1fnzHeO6cV0HNzsFvJSuxxE8=</ds:DigestValue>

</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue Id="xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-sigvalue">Zybb8CVjGc2BCnSSWt/I8GRPZg2fH73NBkihbXMZVW+aDNbglJaVUzZa3HjMMLZ0u84Ev0I504GiaGfRhb68aLmdX05X0oF0oa8fRSizdCXSIr5Q1eoABf2SQThA+4imLeOulqCwK2ShMZH//RQDdqzFY3a6C05hbyNfwOkcJ5YyV5dgAL4PfXOdOTubFGn8z+GOF96vBM/Vzn1CsnWncY55OT2GdTe4+xu5vguHRag6tpo5uOd2Ict8Dtg3prBgEly7xjeScaqKZ2w5zYo09gICXTAyrqREc+RA3sAD+KOz2BZAvdTnY5sLs8Zl6zEdGziHtXD1zgmDshmpZXVtQA==</ds:SignatureValue>

-<ds:KeyInfo Id="xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-keyinfo">

-<ds:X509Data>

<ds:X509Certificate>MIIIezCCBmOgAwIBAgIIYdrV2p9mHpwwDQYJKoZIhvcNAQELBQAwgbQxIzAhBgkqhkiG9w0BCQEWFGluZm9AYW5kZXNzY2QuY29tLmNvMSMwIQYDVQQDExpDQSBBTkRFUyBTQ0QgUy5BLiBDbGFzZSBJSTEwMC4GA1UECxMnRGl2aXNpb24gZGUgY2VydGlmaWNhY2lvbiBlbnRpZGFkIGZpbmFsMRMwEQYDVQQKEwpBbmRlcyBTQ0QuMRQwEgYDVQQHEwtCb2dvdGEgRC5DLjELMAkGA1UEBhMCQ08wHhcNMTgxMDAzMTUyMzAwWhcNMTkxMDAzMTUyMjAwWjCCATgxOzA5BgNVBAkTMkNSIDIzIDY0QiAzMyBFRCBDRU5UUk8gREUgIE5FR09DSU9TIFNJR0xPIFhYSSBBUCAzMSIwIAYJKoZIhvcNAQkBFhNnZXJlbmNpYUBqYWl2YW5hLmNvMRUwEwYDVQQDDAxKQUlWQU7DgSBTQVMxEzARBgNVBAUTCjgxNjAwMzQ0ODExNjA0BgNVBAwTLUVtaXNvciBGYWN0dXJhIEVsZWN0cm9uaWNhIC0gUGVyc29uYSBKdXJpZGljYTErMCkGA1UECxMiRW1pdGlkbyBwb3IgQW5kZXMgU0NEIENyYSAyNyA4NiA0MzESMBAGA1UEChMJTUFOSVpBTEVTMRIwEAYDVQQHEwlNQU5JWkFMRVMxDzANBgNVBAgTBkNBTERBUzELMAkGA1UEBhMCQ08wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDtojCmQKJw/UPvZO2aTYP2/7HbJzHuaSEbvbD42Y9zlX40uCQ5Lapb7C2NYPrir/7hJvIpVFggqqf/GOFIRZpNzTjtq1wIzlu2IUMGWTJusFFaWSLlU2+GheTe+Av3LaIPguTCaRLTIKXxI7bFhtH+SOzsgRYRZiN4OkJGggDc9pWGMDKYvq+CEdcpLlP5INZPgztpfggK2EfqnUZHReScRgv8Cp0qmxy1KFgXvpQ4pKwYtEtt7SUjnIkmBH6s0TxZWoMQHNarbFYP2wrO1VLwxZz3D+uMa0QEfMMMAgqqzjE5PGN6tuVwxdtCvTvUIXJq2UDxJgwdO/n9BOEcZ04FAgMBAAGjggMIMIIDBDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFKhLtPQLp7Zb1KAohRCdBBMzxKf3MDcGCCsGAQUFBwEBBCswKTAnBggrBgEFBQcwAYYbaHR0cDovL29jc3AuYW5kZXNzY2QuY29tLmNvMB4GA1UdEQQXMBWBE2dlcmVuY2lhQGphaXZhbmEuY28wggHxBgNVHSAEggHoMIIB5DCCAeAGDSsGAQQBgfRIAQIGAQIwggHNMEEGCCsGAQUFBwIBFjVodHRwOi8vd3d3LmFuZGVzc2NkLmNvbS5jby9kb2NzL0RQQ19BbmRlc1NDRF9WMy4wLnBkZjCCAYYGCCsGAQUFBwICMIIBeB6CAXQATABhACAAdQB0AGkAbABpAHoAYQBjAGkA8wBuACAAZABlACAAZQBzAHQAZQAgAGMAZQByAHQAaQBmAGkAYwBhAGQAbwAgAGUAcwB0AOEAIABzAHUAagBlAHQAYQAgAGEAIABsAGEAcwAgAFAAbwBsAO0AdABpAGMAYQBzACAAZABlACAAQwBlAHIAdABpAGYAaQBjAGEAZABvACAAZABlACAARgBhAGMAdAB1AHIAYQBjAGkA8wBuACAARQBsAGUAYwB0AHIA8wBuAGkAYwBhACAAKABQAEMAKQAgAHkAIABEAGUAYwBsAGEAcgBhAGMAaQDzAG4AIABkAGUAIABQAHIA4QBjAHQAaQBjAGEAcwAgAGQAZQAgAEMAZQByAHQAaQBmAGkAYwBhAGMAaQDzAG4AIAAoAEQAUABDACkAIABlAHMAdABhAGIAbABlAGMAaQBkAGEAcwAgAHAAbwByACAAQQBuAGQAZQBzACAAUwBDAEQwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuYW5kZXNzY2QuY29tLmNvL0NsYXNlSUkuY3JsMB0GA1UdDgQWBBQk0B1mWVgtkHEGPFfuJlQO3zo/czAOBgNVHQ8BAf8EBAMCBeAwDQYJKoZIhvcNAQELBQADggIBAJqqBlD9QpepmK512qrjuXmK4VVEv6QwCYKETjFnaPj03Sv3vo5+lrpjU9G4oDnlN52I5lpl8BEP2g6SvPwjJw+a48xKogNyInYFrGNksBoVUioR/XSlFelwFXhBBLM9Fm94jISXy4OiQ1ccGwvnSYqsQw84r2pf/ZYZ2wuEFNYE9GRaglxzIe0Fmd/pAzKmznnHzPLYjkw88ImivQ8hJ0AefLV04NLT8XQOf3aqI6xbBaB5UtsELc3ZpJ5BQj+L2RiNTqPqtvqa5NXY25LwR0fj1UGS0EPKyoe32jdGc17AnIG+FDbBfh94H2wicsG89PxgzpDaNw5aqGO7QYivKEQN2PamqZieGmX6ZZGyLS1/g2aetp8XRXe/B8ZzvvhEDzAs8o5V2+PP9bK4dODScR2DLGUF2wm7c/OWpkcMxTfoFU/HHGX2ksKcbbh1Y8PJhdshvhOOt4tVc409BB5WsSJ24fo88pO6PCv5nGbyxs6FkzSTslRLkM67+yoCQcDATCbaHyI0AdrXVFk7pnA1xPYIRCbwt7nPNgKh42xoJRgVnp+TkGJwiAM7lk88b1gGgqIP6ZNY2kYi8ZOjDcFKabHJlFA3LeXMjM9c/MWWvDI5GHN/BbbAizLplFE+EU68H/0oNjmv8tIYdHvgs+BzlTtHZJP/0Tglp1t8YocKT9+o</ds:X509Certificate>
<ds:X509SubjectName>C=CO,ST=CALDAS,L=MANIZALES,O=MANIZALES,OU=Emitido por Andes SCD Cra 27 86 43,2.5.4.12=#132d456d69736f72204661637475726120456c656374726f6e696361202d20506572736f6e61204a75726964696361,2.5.4.5=#130a38313630303334343831,CN=JAIVANÁ SAS,1.2.840.113549.1.9.1=#1613676572656e636961406a616976616e612e636f,STREET=CR 23 64B 33 ED CENTRO DE NEGOCIOS SIGLO XXI AP 3</ds:X509SubjectName>
-<ds:X509IssuerSerial>
<ds:X509IssuerName>C=CO, L=Bogota D.C., O=Andes SCD., OU=Division de certificacion entidad final, CN=CA ANDES SCD S.A. Clase II, EMAILADDRESS=info@andesscd.com.co</ds:X509IssuerName>
<ds:X509SerialNumber>7051183301555789468</ds:X509SerialNumber>
</ds:X509IssuerSerial>
</ds:X509Data>
</ds:KeyInfo>
-<ds:Object>
-<xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" Target="#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5" xmlns:xades141="http://uri.etsi.org/01903/v1.4.1#">
-<xades:SignedProperties Id="xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-signedprops">
-<xades:SignedSignatureProperties>
<xades:SigningTime>2018-10-18T15:35:33Z</xades:SigningTime>
-<xades:SigningCertificate>
-<xades:Cert>
-<xades:CertDigest>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>aaCZ85N8STGDgt3CP2aUawsqMAX8K9oOGAtDzz/7NBA=</ds:DigestValue>
</xades:CertDigest>
-<xades:IssuerSerial>
<ds:X509IssuerName>C=CO, L=Bogota D.C., O=Andes SCD., OU=Division de certificacion entidad final, CN=CA ANDES SCD S.A. Clase II, EMAILADDRESS=info@andesscd.com.co</ds:X509IssuerName>
<ds:X509SerialNumber>7051183301555789468</ds:X509SerialNumber>
</xades:IssuerSerial>
</xades:Cert>
</xades:SigningCertificate>
-<xades:SignaturePolicyIdentifier>
-<xades:SignaturePolicyId>
-<xades:SigPolicyId>
<xades:Identifier>https://facturaelectronica.dian.gov.co/politicadefirma/v2/politicadefirmav2.pdf</xades:Identifier>
<xades:Description>Política de firma para facturas electrónicas de la República de Colombia.</xades:Description>
</xades:SigPolicyId>
-<xades:SigPolicyHash>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>dMoMvtcG5aIzgYo0tIsSQeVJBDnUnfSOfBpxXrmor0Y=</ds:DigestValue>
</xades:SigPolicyHash>
</xades:SignaturePolicyId>
</xades:SignaturePolicyIdentifier>
-<xades:SignerRole>
-<xades:ClaimedRoles>
<xades:ClaimedRole>supplier</xades:ClaimedRole>
</xades:ClaimedRoles>
</xades:SignerRole>
</xades:SignedSignatureProperties>
</xades:SignedProperties>
</xades:QualifyingProperties>
</ds:Object>
</ds:Signature>

**Comment by luisgoncalves** [comment] 2018-10-19 10:36
Posting the entire signature on its own doesn't really help. How are you generating the signature?

There have been multiple open ticket regarding "reference validation errors" from DIAN. The DIAN service which also uses xades4j, which causes confusion. But the problem is that they don't seem to include enough error details on the response, and with that, I can't really help.

**Comment by Mariluz08** [comment] 2018-10-19 15:50
I am using the crypto library.
the code is :

ObjectContainer qPropsXmlObj = new ObjectContainer(doc);
                    qPropsXmlObj.appendChild(qualifyingPropsElem);

                    Element signedPropsElem = DOMHelper.getFirstChildElement(qualifyingPropsElem);
                    DOMHelper.setIdAsXmlId(signedPropsElem, "xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-signedprops");

                    DOMStructure qualifPropStruct = new DOMStructure(qualifyingPropsElem);
                    List<DOMStructure> xmlObj = new ArrayList<>();
                    xmlObj.add(qualifPropStruct);

                    XMLObject xmlObject = fac.newXMLObject(xmlObj,
                            null, null, null);

                    SignatureMethod signatureMethod = fac.newSignatureMethod("http://www.w3.org/2001/04/xmldsig-more#rsa-sha256", null);

                    KeyInfoFactory kif = fac.getKeyInfoFactory();

                    X509Data xd = kif.newX509Data(Collections.singletonList(cert));
                    KeyInfo keyInfo = kif.newKeyInfo(Collections.singletonList(xd), "xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-keyinfo");

                    SignedInfo si = fac.newSignedInfo(fac.newCanonicalizationMethod(CanonicalizationMethod.INCLUSIVE,
                            (C14NMethodParameterSpec) null),
                            signatureMethod, listReference);

                    XMLSignature xmlSignature = fac.newXMLSignature(si,
                            keyInfo, Collections.singletonList(xmlObject), "xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5", "xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-sigvalue");

                    DOMSignContext signContext = new DOMSignContext(ks.getKey(alias, password), assertionNode);
                    signContext.setDefaultNamespacePrefix("ds");

                    doc.normalizeDocument();                 
                    xmlSignature.sign(signContext);

**Comment by Mariluz08** [comment] 2018-10-19 16:00
I validate the signature before to save  and the signature passed, but, when I send to the DIAN, the signature failed.  I save de document with this code:

  TransformerFactory tFactory = TransformerFactory.newInstance();
                Transformer transformer = tFactory.newTransformer();
                transformer.setOutputProperty(OutputKeys.INDENT, "no");
                transformer.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
                transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "no");
                DOMSource source = new DOMSource(documento);
                StreamResult result = new StreamResult(new File(ruta));
                transformer.transform(source, result);

@luisgoncalves

**Comment by luisgoncalves** [comment] 2018-10-19 16:14
@Mariluz08 I don't see any usage of xades4j in your code. You seem to be building everything using Apache Santuario manually. I'm not sure I can help you with that.

Anyway, if you say you can validate it prior to saving, it's very likely related to an issue during save. You should try validating it in your code after saving, to further troubleshoot.

Other wild guesses for you to investigate:

- How are you creating `listReference`? Does it contain a reference covering the signed properties element?
- Are you sure about the usage of that `List<DOMStructure> xmlObj` ?

**Comment by Mariluz08** [comment] 2018-10-19 16:28
@luisgoncalves 
I am creating listReference with this code:

    Reference ref = fac.newReference("", fac.newDigestMethod(DigestMethod.SHA512, null),
                            Collections.singletonList(fac.newTransform(Transform.ENVELOPED, (TransformParameterSpec) null)),
                            null, "xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-ref0");
                    // referencia key info

                    Reference refKeyinfo = fac.newReference("#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-keyinfo", fac.newDigestMethod(DigestMethod.SHA512, null),
                            null, null, null);

                    Reference refSigned = fac.newReference("#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-signedprops", fac.newDigestMethod(DigestMethod.SHA512, null),
                            null, "http://uri.etsi.org/01903#SignedProperties", null);

                    
                    List<Reference> listReference = new ArrayList<>();
                    listReference.add(ref);
                    listReference.add(refKeyinfo);
                    listReference.add(refSigned);

And I add this list:

    SignedInfo si = fac.newSignedInfo(fac.newCanonicalizationMethod(CanonicalizationMethod.INCLUSIVE,
                            (C14NMethodParameterSpec) null),
                            signatureMethod, listReference);




I have been trying in many ways but the DIAN always rejects me..
other method that I used is:

   ObjectContainer object;
                object = new ObjectContainer(documento);
                object.appendChild(qualifyingPropsElem);
                assertionNode.appendChild(signature.getElement());
                signature.getElement().appendChild(object.getElement());

                signature.setId("xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5");
                signature.addDocument("", getTransforms(documento), DigestMethod.SHA512, "xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-ref0", null);
                signature.addDocument("#" + "xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-keyinfo", null, DigestMethod.SHA512);
                signature.addDocument("#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-signedprops", getTransformsSignedProps(documento), DigestMethod.SHA512, null, "http://uri.etsi.org/01903#SignedProperties");

                signature.addKeyInfo(signingCert);
                signature.getKeyInfo().setId("xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-keyinfo");

                NodeList node = documento.getElementsByTagName("ds:SignatureValue");
                Element signatureValue = (Element) node.item(0);
                signatureValue.setAttribute("Id", "xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-sigvalue");
                documento.normalizeDocument();
                signature.sign(ks.getKey(alias, PASSWORD))


BUT the error is the same. 

com.indra.mmdd.signature.exceptions.ValidateException: xades4j.verification.ReferenceValueException: Reference '#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-signedprops' cannot be validated

**Comment by luisgoncalves** [comment] 2018-10-21 20:05
@Mariluz08 I still don't see any usage of xades4j in your code. It's really hard to figure out where the problem is with 1) that kind of code, that builds everything by hand; 2) no additional error details from the DIAN service.
I suggest that you try adding one reference at a time and validate each resulting signature locally (build it step-by-step) to try to debug.

I'm closing this issue, since there's isn't a problem with xades4j usage.

**Closed by luisgoncalves** 2018-10-21 20:05 UTC

**Comment by genyus00** [comment] 2019-11-23 23:26
Hola .. de donde sale la clave   88fbfc45-3be2-4c4a-83ac-0796e1bad4c5 ?

**Comment by fdomoreno** [comment] 2023-05-13 08:19
@Mariluz08 option: System.setProperty("org.apache.xml.security.ignoreLineBreaks", "true");
