### ISSUE TITLE
Invalid key entry password

### ISSUE THREAD

**Issue by RodHR** [luisgoncalves/xades4j#209] opened 2020-08-14 03:09 UTC
Hi.

I've developed an application using your library but now I'm facing the following problem:

I'm trying to call the sign method of the XadesSigner using the following code:

```java
import org.apache.commons.io.IOUtils;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import xades4j.algorithms.EnvelopedSignatureTransform;
import xades4j.production.DataObjectReference;
import xades4j.production.SignedDataObjects;
import xades4j.production.XadesEpesSigningProfile;
import xades4j.production.XadesSigner;
import xades4j.properties.*;
import xades4j.providers.KeyingDataProvider;
import xades4j.providers.SignaturePolicyInfoProvider;
import xades4j.providers.SignaturePropertiesCollector;
import xades4j.providers.SignaturePropertiesProvider;
import xades4j.providers.impl.FileSystemKeyStoreKeyingDataProvider;

import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class Signer {

    public void signDocument(Document doc, String cert, String pass, String signedBill, String policy, String policyFilePath)
            throws Exception {

        KeyingDataProvider kdp = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                cert,
                new FirstCertificateSelector(),
                new DirectPasswordProvider(pass),
                new DirectPasswordProvider(pass),
                true);

        // politica
        SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider() {
            @Override
            public SignaturePolicyBase getSignaturePolicy() {
                try {
                    ObjectIdentifier objIdentifier = new ObjectIdentifier(policy);
                    InputStream policyDocumentStream = new FileInputStream(policyFilePath);
                    byte[] bytes = IOUtils.toByteArray(policyDocumentStream);

                    return new SignaturePolicyIdentifierProperty(objIdentifier, bytes);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                return null;
            }
        };
        // Role
        XadesSigner signer = new XadesEpesSigningProfile(kdp, policyInfoProvider)
                .withSignaturePropertiesProvider(new SignaturePropertiesProvider() {
                    @Override
                    public void provideProperties(SignaturePropertiesCollector arg0) {
                        SigningTimeProperty sigTime = new SigningTimeProperty();
                        arg0.setSignerRole(new SignerRoleProperty().withClaimedRole("supplier"));
                        arg0.setSigningTime(sigTime);
                    }
                }).newSigner();

        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        dbf.setNamespaceAware(true);

        NodeList nodes = doc.getElementsByTagName("ext:UBLExtensions");

        //Selección de elemento para incluir firma digital
        NodeList nodes2 = doc.getElementsByTagName("ext:ExtensionContent");
        Element elem = (Element) nodes2.item(1);

        //Firma de xml
        DataObjectDesc dataObjRef = (new DataObjectReference("")).withTransform(new EnvelopedSignatureTransform());
        signer.sign(new SignedDataObjects(new DataObjectDesc[]{dataObjRef}), elem);

        TransformerFactory tFactory = TransformerFactory.newInstance();
        Transformer transformer = tFactory.newTransformer();
        DOMSource source = new DOMSource(doc);
        StreamResult result = new StreamResult(new File(signedBill));
        transformer.transform(source, result);

    }

}
```

When I call the method once, it works fine (I get my xml file well signed), but, when I call the method twice (because I need to sign a certain amount of documents), I'm getting the following error:

```bash
xades4j.providers.SigningCertChainException: Selected certificate doesn't match a key and corresponding certificate chain
```

Does it make sense affirm that at certain point the certificate is being modified? 

Could you, please, guide me?

Thanks in advance.

**Comment by luisgoncalves** [comment] 2020-08-17 09:37
Hello,

Do you have a stack trace / line number, just to be sure where the exception is being thrown in the xades4j source?

I don't think the certificate is being modified... Can you try creating the `FileSystemKeyStoreKeyingDataProvider` only once?

**Comment by RodHR** [comment] 2020-08-17 17:37
Luis.

I've implemented a singleton pattern as you can see in the following code:

```java
public class Signer {

    public static Signer instance;

    private boolean wasInvoked;

    private KeyingDataProvider kdp;

    private SignaturePolicyInfoProvider policyInfoProvider;

    private XadesSigner signer;

    private Signer() {
        this.wasInvoked = false;
    }

    public static Signer getInstance() {
        if (instance == null) {
            instance = new Signer();
        }

        return instance;
    }

    public void signDocument(Document doc, String cert, String pass, String signedBill, String policy, String policyFilePath)
            throws Exception {

        if (!wasInvoked) {

            kdp = new FileSystemKeyStoreKeyingDataProvider(
                    "pkcs12",
                    cert,
                    new FirstCertificateSelector(),
                    new DirectPasswordProvider(pass),
                    new DirectPasswordProvider(pass),
                    true);

            // politica
            policyInfoProvider = new SignaturePolicyInfoProvider() {
                @Override
                public SignaturePolicyBase getSignaturePolicy() {
                    try {
                        ObjectIdentifier objIdentifier = new ObjectIdentifier(policy);
                        InputStream policyDocumentStream = new FileInputStream(policyFilePath);
                        byte[] bytes = IOUtils.toByteArray(policyDocumentStream);

                        return new SignaturePolicyIdentifierProperty(objIdentifier, bytes);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    return null;
                }
            };
            // Role
            signer = new XadesEpesSigningProfile(kdp, policyInfoProvider)
                    .withSignaturePropertiesProvider(new SignaturePropertiesProvider() {
                        @Override
                        public void provideProperties(SignaturePropertiesCollector arg0) {
                            SigningTimeProperty sigTime = new SigningTimeProperty();
                            arg0.setSignerRole(new SignerRoleProperty().withClaimedRole("supplier"));
                            arg0.setSigningTime(sigTime);
                        }
                    }).newSigner();

            wasInvoked = true;

        }

        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        dbf.setNamespaceAware(true);

        //Selección de elemento para incluir firma digital
        NodeList nodes2 = doc.getElementsByTagName("ext:ExtensionContent");
        Element elem = (Element) nodes2.item(1);

        //Firma de xml
        DataObjectDesc dataObjRef = (new DataObjectReference("")).withTransform(new EnvelopedSignatureTransform());
       
        //Document Signing
        signer.sign(new SignedDataObjects(new DataObjectDesc[]{dataObjRef}), elem);

        TransformerFactory tFactory = TransformerFactory.newInstance();
        Transformer transformer = tFactory.newTransformer();
        DOMSource source = new DOMSource(doc);
        StreamResult result = new StreamResult(new File(signedBill));
        transformer.transform(source, result);

    }

}
```
And the error that I'm getting is:

```bash
xades4j.providers.SigningKeyException: Invalid key entry password
	at xades4j.providers.impl.KeyStoreKeyingDataProvider.getSigningKey(KeyStoreKeyingDataProvider.java:252)
	at xades4j.production.SignerBES.sign(SignerBES.java:271)
	at xades4j.production.SignerBES.sign(SignerBES.java:129)
	...
Caused by: java.security.UnrecoverableKeyException: Get Key failed: pad block corrupted
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:435)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetEntry(PKCS12KeyStore.java:1306)
	at java.security.KeyStore.getEntry(KeyStore.java:1521)
	at xades4j.providers.impl.KeyStoreKeyingDataProvider.getSigningKey(KeyStoreKeyingDataProvider.java:245)
	... 8 more
Caused by: javax.crypto.BadPaddingException: pad block corrupted
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
	at javax.crypto.Cipher.doFinal(Cipher.java:2168)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:371)
	... 11 more
```

Any idea?

**Comment by luisgoncalves** [comment] 2020-08-17 22:05
I've found [this issue](https://github.com/bcgit/bc-java/issues/306) that mentions a problem with BC provider when the key entry password is different from the key store password. Is this your case? Are you setting BC as a "default" or similar?

If that's not the case, I suggest isolating the usage of `FileSystemKeyStoreKeyingDataProvider` in a unit test and mimic the usage that xades4j does of it, 2 times:

- call `getSigningCertificateChain()`
- call `getSigningKey()` passing in the first certificate of the list returned by the previous method
- repeat once more

**Comment by luisgoncalves** [comment] 2020-08-31 21:06
Any updates?

**Comment by RodHR** [comment] 2020-09-19 21:38
Hello @luisgoncalves 
Sorry for the late answer.
At last, the problem was de library version that I were using. I have to downgrade to 1.3.1  
Thanks for your attention.

**Comment by luisgoncalves** [comment] 2020-09-19 22:36
I was hoping that we could find the root cause, in case there is a bug.. It could also be a bug in one of the dependencies, since downgrading probably changed their versions.

I'm closing this issue. Please reopen if you're willing to dig a bit more.

**Closed by luisgoncalves** 2020-09-19 22:36 UTC
