### ISSUE TITLE
Is ds:X509SubjectName tag included in API?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luisgoncalves/xades4j#78] opened 2015-08-06 22:05 UTC
```
HI,
ds:X509SubjectName tag is also not added.
Any suggestion about it as i read old issue that it does not exist in api.

Regards
Jay

```

Original issue reported on code.google.com by `jay...@gmail.com` on 18 Mar 2014 at 12:12

**Comment by luisgoncalves** [comment] 2017-04-21 21:35
Duplicate of #43

**Closed by luisgoncalves** 2017-04-21 21:35 UTC
Labels: auto-migrated, duplicate
